development:
  adapter: postgresql
  encoding: unicode
  database: app_development
  pool: 5
  username: yunxuan
  password: 19900818

test: &test
  adapter: postgresql
  encoding: unicode
  database: app_test
  pool: 5
  username: yunxuan
  password: 19900818

production:
  adapter: postgresql
  encoding: unicode
  database: app_production
  pool: 5
  username: yunxuan
  password: 19900818

cucumber:
  <<: *test
